DROP TABLE IF EXISTS GEOGRAPHY_COLUMNS;

CREATE TABLE GEOGRAPHY_COLUMNS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  city_name VARCHAR(250) NOT NULL
);


DROP TABLE IF EXISTS WEBSITE_STATUS;

CREATE TABLE WEBSITE_STATUS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  site VARCHAR(250) NOT NULL
);
